# Generated by Django 2.1.7 on 2019-06-03 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lst',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sc',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t1',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='t2',
            options={'managed': True},
        ),
    ]
